---
- name: Create app directory
  file:
    path: /opt/app
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Clone git repo
  git:
    repo: https://github.com/warrenpearson/simple-flask-app.git
    dest: /opt/app/simple-flask-app
  
- name: Generate app config
  template:
    src: config.yml.j2
    dest: "/opt/app/simple-flask-app/config/config.yml"
