---
- name: Create app directory
  file:
    path: /opt/app
    state: directory
    owner: ubuntu
    group: ubuntu
  
- name: Generate app config
  template:
    src: config.yml.j2
    dest: "/opt/app/config.yml"
