---
- name: Run stop script
  command:
    chdir: /opt/app/simple-flask-app
    cmd: ./stop.sh
  become: yes
  become_user: ubuntu

- name: Run start script
  command:
    chdir: /opt/app/simple-flask-app
    cmd: ./start.sh
  become: yes
  become_user: ubuntu
